version: '3.7'
services:
  events.104.com.tw:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: "104z-node-12"
    volumes:
      - ../:/usr/src/app
      - nodemodules:/usr/src/app/node_modules:rw
    ports:
      - 3000:3000
    tty: true
    networks:
      - webnet
  #   depends_on:
  #     - nginx
  # nginx:
  #   image: nginx:1.18
  #   container_name: "104z-nginx"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #     - ./certificate/wildcard.104-dev.com.tw.pem:/etc/nginx/wildcard.104-dev.com.tw.pem
  #     - ./certificate/wildcard.104-dev.com.tw-key.pem:/etc/nginx/wildcard.104-dev.com.tw-key.pem
  #   networks:
  #     - webnet
  #   ports:
  #     - 80:80
  #     - 443:443
networks:
  webnet:
volumes:
  nodemodules: