version: '3.7'
services:
  events.104.com.tw:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: "104z-node-12"
    volumes:
      - ../:/usr/src/app
      - nodemodules:/usr/src/app/node_modules:rw
    ports:
      - 3000:3000
    tty: true

volumes:
  nodemodules: